# Generated by Django 3.2.9 on 2021-12-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(default=380966834593, max_length=13),
        ),
    ]
