# Generated by Django 3.2.9 on 2021-12-25 19:15
# flake8: noqa
from django.db import migrations, models
import students.validator


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default=380967195593, max_length=13, validators=[students.validator.validate_phone]),
        ),
    ]
