# Generated by Django 3.2.9 on 2022-01-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_teacher_phone'),
        ('students', '0003_auto_20211225_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(to='teacher.Teacher'),
        ),
    ]
