# Generated by Django 3.2.9 on 2022-01-20 15:06

from django.db import migrations
# flake8: noqa


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20220120_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='student',
        ),
        migrations.RemoveField(
            model_name='group',
            name='teacher',
        ),
    ]
