# Generated by Django 3.2.9 on 2022-01-20 15:09
# flake8: noqa

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_auto_20220120_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='teacher',
        ),
    ]
