# Generated by Django 3.2.9 on 2022-01-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_contact'),
        ('group', '0006_group_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='student',
        ),
        migrations.AddField(
            model_name='group',
            name='student',
            field=models.ManyToManyField(to='students.Student'),
        ),
    ]
